type: "tgi"
args:
  name: "Qwen2.5-7B-Instruct"
  backend_url: "http://localhost:8080"
  system_prompt: ""
  record_template: "[INST]The following are multiple choice questions (with answers) with context:\n\n{context}Question: {question}\n{choices}[/INST]Answer: "
run_args:
  max_new_tokens: 30
  stop_sequences: 
    - "\n\n"